Source.cpp
MAX
Referenced by createFood, fCheck, fDraw, main.
void fClean()
Referenced by main.
NodeManager createFood(NodeManager &head)
References NodeManager::getNode, MAX, Node::setShape.
void fReset(NodeManager &head)
References NodeManager::getNode, Node::getPNext, Node::setPNext, Node::setPosition.
Referenced by fCheck.
void fDraw(NodeManager &head, NodeManager &food)
References Node::getCheck, Node::getExist, NodeManager::getNode, Node::getPNext, Node::getShape, MAX.
Referenced by main.
void keyDown(Node &head)
References Node::getDirect, Node::setDirect, Node::setSpeed.
Referenced by main.
void fMoving(NodeManager &head, NodeManager &food, bool &b_create_food)
References Node::addNode, Node::getDirect, NodeManager::getNode, Node::getPNext, Node::getX, Node::getY, Node::movePosition, Node::setPosition.
Referenced by main.
void fCheck(NodeManager &head)
References fReset, NodeManager::getNode, Node::getX, Node::getY, MAX, Node::setDirect, Node::setSpeed.
Referenced by main.
int main()
References fCheck, fClean, fDraw, fMoving, NodeManager::getNode, keyDown, MAX, Node::setPNext, Node::setShape.