NodeManager
Node* NodeManager::m_node
Referenced by getNode, NodeManager, ~NodeManager.
NodeManager::NodeManager()
NodeManager::NodeManager(int i_x, int i_y)
References m_node.
Node * NodeManager::getNode()
References m_node.
Referenced by Node::addNode, createFood, fCheck, fDraw, fMoving, fReset, main.
NodeManager::~NodeManager()
References m_node.