Node
int Node::mi_x
Referenced by addNode, getCheck, getX, movePosition, setPosition.
int Node::mi_y
Referenced by addNode, getCheck, getY, movePosition, setPosition.
int Node::mi_direct
Referenced by getDirect, setDirect.
int Node::mi_speed
Referenced by getSpeed, setSpeed.
bool Node::mb_exist
Referenced by getExist, setExist.
NodeManager* Node::mp_next
Referenced by addNode, getPNext, setPNext.
char Node::mc_shape
Referenced by getShape, setShape.
Node::Node()
Node::Node(int i_x, int i_y)
void Node::setPosition(int i_x, int i_y)
References mi_x, mi_y.
Referenced by addNode, fMoving, fReset.
void Node::movePosition(int i_mx, int i_my)
References mi_x, mi_y.
Referenced by fMoving.
void Node::setShape(char c_shape)
References mc_shape.
Referenced by addNode, createFood, main.
void Node::setDirect(int i_direct)
References mi_direct.
Referenced by fCheck, keyDown.
void Node::setExist(bool b_exist)
References mb_exist.
Referenced by addNode.
void Node::setSpeed(int i_speed)
References mi_speed.
Referenced by fCheck, keyDown.
int Node::getSpeed()
References mi_speed.
bool Node::getExist()
References mb_exist.
Referenced by fDraw.
char Node::getShape()
References mc_shape.
Referenced by fDraw.
int Node::getDirect()
References mi_direct.
Referenced by fMoving, keyDown.
int Node::getX()
References mi_x.
Referenced by addNode, fCheck, fMoving.
int Node::getY()
References mi_y.
Referenced by addNode, fCheck, fMoving.
void Node::setPNext(NodeManager *p_next)
References mp_next.
Referenced by addNode, fReset, main.
NodeManager * Node::getPNext()
References mp_next.
Referenced by fDraw, fMoving, fReset.
bool Node::getCheck(int i_x, int i_y)
References mi_x, mi_y.
Referenced by fDraw.
void Node::addNode(NodeManager &food)
References NodeManager::getNode, getX, getY, mi_x, mi_y, mp_next, setExist, setPNext, setPosition, setShape.
Referenced by fMoving.