// AtlSvcAuth.idl : AtlServiceTest의 IDL 소스입니다.
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(AtlSvcAuth.tlb) 및 마샬링 코드가 생성됩니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(15E06E5E-D0E7-42D5-BF87-3C1B414C2592),
	version(1.0),
]
library AtlServiceTestLib
{
	importlib("stdole2.tlb");
};

