// AtlSvcApc.idl : AtlSvcApc의 IDL 소스입니다.
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(AtlSvcApc.tlb) 및 마샬링 코드가 생성됩니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(50BA00E0-8BE1-4F7E-BECA-21E276A6F559),
	version(1.0),
]
library AtlSvcApcLib
{
	importlib("stdole2.tlb");
};

